console.time("Your Code Took");
console.log("Hello World");
console.log(5 + 6);
console.log(25);
console.log(true);
console.log([15, 5, 2, 19]);
console.log({ virali: "25", vijay: "26" });
console.table({ virali: "25", vijay: "26" });
console.warn("This is a Warning");
// console.clear();
console.timeEnd("Your Code Took");
// console.assert(age > 189, "Age>189 is not possible");
console.error("This is an error");
